### PR TITLE
[RFC] Check unknown types and functions in sample applications

### PR DESCRIPTION
**Pull request by lucafavatella**
Please refer to commit message for details.

### CODE REVIEW

**Comment by lucafavatella** [comment]
CI reports the following Dialyzer errors:
* `:0: Unknown type cow_http_te:decode_ret/0` - apparently this only needs inclusion of `cowlib` in PLT (see `plt_extra_apps` in rebar3 rebar.config)
* `:0: Unknown type cowboy_router:route_match/0` - addressed in to-be-merged https://github.com/inaka/cowboy-trails/pull/74
* `:0: Unknown type sumo_rest:options/0` - tracked in #87

**Comment by lucafavatella** [comment]
Tagged as request for comments.
Maybe the sample sumo_rest application shall be moved to a separate repo?

**Comment by elbrujohalcon** [comment]
I don't particularly like this approach of not including `test` folder in dialyzer checks, as stated here: https://github.com/inaka/katana-test/issues/38#issuecomment-286156533

**Comment by elbrujohalcon** [comment]
Instead I would prefer to either…

- add common_test to the PLT
- add `dialyzer(…).` attributes to the test modules so that those particular warnings are avoided, and not all of the code unchecked.

**Comment by elbrujohalcon** [comment]
inaka/cowboy-trails#74 merged

**Comment by lucafavatella** [comment]
Thanks for the comments. I am unable to complete this for now - I opened ticket #89 for tracking and I am closing this.

**Pull request closed without merging**
